### ISSUE TITLE
Issue with usernames starting with -

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [xavdid/reddit-user-to-sqlite#11]
Usernames with a leading `-` are apparently being parsed as a command-line arg:

```
reddit-user-to-sqlite user -some_username
```
or
```
reddit-user-to-sqlite user "-some_username"
```
lead to
```
Error: No such option: -s
```

But this works:
```
reddit-user-to-sqlite user /u/-some_username
```

**Comment by xavdid** [comment]
Yep, see discussion in #6- I'll get a line added to the FAQ that mentions this.

**Comment by xavdid** [comment]
I've added info about this to the FAQs.
