### ISSUE TITLE
Full post text?

### ISSUE THREAD

**Issue by leehauser** [xavdid/reddit-user-to-sqlite#14]
Perhaps I'm doing something wrong, but looking at the downloaded data in Datasette doesn't show me the full text of my longer posts; they just trail off with an ellipsis.

**Comment by xavdid** [comment]
I believe this is a limitation of Datasette. It may be configurable, but I'm not sure. I can look into it.

**Comment by xavdid** [comment]
This is configurable in Datasette: https://docs.datasette.io/en/stable/settings.html#truncate-cells-html

I'll add a note to the docs.

**Comment by leehauser** [comment]
Thanks very much!

**Comment by xavdid** [comment]
I've added info about this to the FAQs.
