### ISSUE TITLE
Include saved posts

### ISSUE THREAD

**Issue by fugkco** [xavdid/reddit-user-to-sqlite#2]
Anything that's on `https://www.reddit.com/user/<username/saved/`

**Comment by Robin-Law** [comment]
Agreed! This would be invaluable to me, as I'm mostly a lurker, but I do save a lot of posts that I want to refer back to later.

**Comment by xavdid** [comment]
I can probably make this happen! I'll look into it next week.

**Comment by quarkw** [comment]
Saved comments too would be great! Both are also included as CSVs in the GDPR archive

**Comment by xavdid** [comment]
Ok, I've got a (probably) working version of this in https://github.com/xavdid/reddit-user-to-sqlite/pull/16

Before I merge & release, does someone mind trying it out? Instructions:

1. duplicate the database you're going to work on in case something goes wrong
2. clone this repo, check out the `TASK-146-add-saved-support` branch
3. run `python -m venv .venv`
4. run `source ./.venv/bin/activate`
5. run `pip install .`
6. run the `archive` command targeting your existing (preferred) database: `reddit-user-to-sqlite archive ~/some/path`

It adds saved comments and posts to their own table, which has the same features and columns as the original `posts` and `comments` tables.

If nothing goes wrong and this does what you want, I'll get it released!

**Comment by xavdid** [comment]
This has been released as part of 0.4.0. Please let me know what you think!
