### ISSUE TITLE
ValueError: Received API error from Reddit (code 403): Forbidden

### ISSUE THREAD

**Issue by a-b** [xavdid/reddit-user-to-sqlite#20]
Any thoughts is this is permanent?

**Comment by xavdid** [comment]
This may have been a temporary issue on Reddit's end - I just ran it a few times and it complete as expected. Hopefully it's not emblematic of what's to come with the API.

I'll close this issue for now, but please reopen if this continues to be an issue (before June 30th; after that, all bets are off).
