### ISSUE TITLE
Ignorant to what am I doing wrong with metadata.json 

### ISSUE THREAD

**Issue by rarelygoeshere** [xavdid/reddit-user-to-sqlite#21]
Hello, I've recently come to be aware of this from your post on reddit, and I've been struggling with the final step of creating a metadata.json file, as I keep getting the error seen in file attached. Changing the txt file into .json seems easy enough, and copy pasting the content was too, yet when I ran datasette reddit.db --metadata metadata.json, it didn't work. I hope you might be able to help me understand this

Disclaimer: I'm very new to datasette and am a layman in general, with very few, if any, knowledge of CLI, so I hope you may excuse my ignorance on things. Thank you.
![screenshot_1687679280](https://github.com/xavdid/reddit-user-to-sqlite/assets/125143953/52529bee-7130-4afc-a605-7425727dfd1c)

**Comment by xavdid** [comment]
No worries at all! CLI can be tough.

I've got two questions-

1. Does running `datasette` work for you if you don't include the `--metadata` arg? 
2. do both `metadata.json` and `reddit.db` show up if you run the `dir` command?

**Comment by rarelygoeshere** [comment]
Hello there, thanks for stopping by! Here are my answers to your questions:
1. Running datasette seems to work fine for me without --metadata, as other cmds like --help and --open appears to be normal, as seen below.
![screenshot_1687720337](https://github.com/xavdid/reddit-user-to-sqlite/assets/125143953/fb0546d7-b655-45a1-b0f6-16ec9dd0ccb4)
![screenshot_1687720171](https://github.com/xavdid/reddit-user-to-sqlite/assets/125143953/a02da24d-46b9-468b-8d93-f55e4a19db7f)
![screenshot_1687720162](https://github.com/xavdid/reddit-user-to-sqlite/assets/125143953/e57334ba-9db3-4c97-9c05-d6d81fd94fdc)

Just out of curiosity, I typed datasette reddit.db --metadata metadata.json sans --metadata and the result obviously didn't do anything.
![screenshot_1687720469](https://github.com/xavdid/reddit-user-to-sqlite/assets/125143953/0a3fcfbf-5f76-4fc3-a10e-a862f27075a6)
2. It appears neither metadata.json or reddit.db shows up for me when I input dir. I did it 2 times, as seen below.
![Dir command C drive](https://github.com/xavdid/reddit-user-to-sqlite/assets/125143953/9c9dc40d-ed19-4a0f-9733-765ffa69ebc3)
![Dir command C drive 2](https://github.com/xavdid/reddit-user-to-sqlite/assets/125143953/1879f951-490f-4d7c-9f3f-99fbd76b6349)

Hope these answers help your assessment!

**Comment by xavdid** [comment]
Ah, cool.

So when you run CLI commands, they're run from a directory (known as the "current directory"). From your screenshots, it looks like you're in `C:\Users\admin-pc` and then the root of your `C:\` drive.

Datasette looks for the `reddit.db` (and `metadata.json`) in the directory you run the command from. So if the `reddit.db` file isn't in `C:\Users\admin-pc`, then you get the error you're seeing.

To fix this, you need to do 2 things:

1. Find where your `reddit.db` file is
2. use the `cd` (change directory) command to navigate your terminal to where that file is

Once there, `datasette` will work as expected. If you put `metadata.json` in that folder as well, it'll get picked up automatically.

Does that make sense?

**Comment by rarelygoeshere** [comment]
> Ah, cool.
> 
> So when you run CLI commands, they're run from a directory (known as the "current directory"). From your screenshots, it looks like you're in `C:\Users\admin-pc` and then the root of your `C:\` drive.
> 
> Datasette looks for the `reddit.db` (and `metadata.json`) in the directory you run the command from. So if the `reddit.db` file isn't in `C:\Users\admin-pc`, then you get the error you're seeing.
> 
> To fix this, you need to do 2 things:
> 
> 1. Find where your `reddit.db` file is
> 2. use the `cd` (change directory) command to navigate your terminal to where that file is
> 
> Once there, `datasette` will work as expected. If you put `metadata.json` in that folder as well, it'll get picked up automatically.
> 
> Does that make sense?

Ahh, I see, then. That makes sense. I'll do so right away.

**Comment by xavdid** [comment]
Awesome! Glad that worked out. I'll go ahead and close this, but I hope this has been illuminating 😅
