### ISSUE TITLE
should mention that it only gets the 999 most recent comments

### ISSUE THREAD

**Issue by llimllib** [xavdid/reddit-user-to-sqlite#4]
I don't _think_ there's anything you can do about this, I asked about it when I wrote [my backup script](https://github.com/llimllib/backupreddituser/blob/master/backup.py) (9 years ago!)

**Comment by llimllib** [comment]
Also probably worth noting that this script truncates long comments

**Comment by xavdid** [comment]
yeah, good call. I can update the reame. 

I'm not aware of the truncation- can you link a comment that's getting truncated? I'm not sure if it's my side or Reddit's.

**Comment by llimllib** [comment]
Sure, [this is the comment I noticed it on](https://old.reddit.com/r/ultimate/comments/dbkeuz/what_are_elite_womens_mixed_and_mens_practices/f22vpbz/?context=10)

**Comment by llimllib** [comment]
Actually that was just datasette truncating it!
