### ISSUE TITLE
Cannot save usernames starting with dash "-"

### ISSUE THREAD

**Issue by pgagnidze** [xavdid/reddit-user-to-sqlite#6]
`$ reddit-user-to-sqlite user -any-username-here` fails with **_No such option_**

It thinks that we are passing an option when starting with dash

**Comment by xavdid** [comment]
Ah interesting. 

Does it work if you do either:

- `"-username"`
- `... user -- -username`

**Comment by pgagnidze** [comment]
Just found it works fine with `$ reddit-user-to-sqlite user -- -username`

It is not an issue with this package specifically, but I recommend adding it in the FAQ or somewhere in README.

Thanks!

**Comment by xavdid** [comment]
I've added info about this to the FAQs.
