### ISSUE TITLE
Error: "comments.csv not found in the expected spot."

### ISSUE THREAD

**Issue by RedBaza** [xavdid/reddit-user-to-sqlite#7]
$ reddit-user-to-sqlite archive username
loading data found in archive at username into reddit.db

...

  File "/home/user/.local/pipx/venvs/reddit-user-to-sqlite/lib/python3.10/site-packages/reddit_user_to_sqlite/csv_helpers.py", line 14, in validate_and_build_path
    raise ValueError(
ValueError: Ensure path "username" points to an unzipped Reddit GDPR archive folder; comments.csv not found in the expected spot.

**Comment by xavdid** [comment]
Is your archive in a folder named `username`? You don't need to specify a username for the archive, just a filepath.

**Comment by RedBaza** [comment]
I did not specify any file path. I installed via pipx and ran the command. Is there another step?

**Comment by xavdid** [comment]
There are two commands:

- `user YOUR_USERNAME_HERE` to pull data from the API on any user 
- `archive FILEPATH` to ingest the archive at a given filepath

Sounds like you want the `user` command, not archive.

**Comment by RedBaza** [comment]
Now I'm extra confused. 

In another issue thread it said that Reddit restricts the output in the user command, but you can "use the archive command to ingest your GDPR archive, which lets you fetch and populate the full history."

To ingest MY GDPR archive (rather than everyone's) I imagine the archive command would need to involve my username, but it looks like it does not.

**Comment by xavdid** [comment]
Correct- your archive only has your data, so it reads your username automatically. All it needs is a filepath. 

If you're loading data from the API about a user, you need that user's name.

**Comment by xavdid** [comment]
I don't think there's any action on my end for this one - check out [the docs](https://github.com/xavdid/reddit-user-to-sqlite#archive) on the `archive` command and let me know if you have further questions.
