### ISSUE TITLE
Is there a way to get more than 1k comments?

### ISSUE THREAD

**Issue by e40** [xavdid/reddit-user-to-sqlite#9]
My account is 17 yrs old.  I would like to get all the comments.  Thanks.

**Comment by xavdid** [comment]
See #5 - the 1k limit is a Reddit restriction. You need to load data from your GDPR archive.

**Comment by e40** [comment]
OK, I've done that.  Is there a difference between GDPR and CA requests?

**Comment by xavdid** [comment]
I don't believe they're different, but I couldn't confirm (there's a timeout between requests)

**Comment by e40** [comment]
Thanks.
